"""Audit causal mean-model candidates before running full portfolio replays.

The output is intentionally lightweight: it scores date-varying daily mu panels
against next close-to-close returns using only signals generated by
``build_rolling_mean_route_a_override.py``.  Use this as the first filter before
creating Route-A override directories and running the full pipeline.
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
from pathlib import Path

import numpy as np
import pandas as pd

try:
    from fund_pool_builder import build_rolling_mean_route_a_override as builder
except ModuleNotFoundError:  # Allows direct execution from the fund_pool_builder directory.
    import build_rolling_mean_route_a_override as builder  # type: ignore[no-redef]


DEFAULT_CANDIDATES = "rolling_mean,ewma60,ewma120,multi_window_mean,momentum60,vol_adjusted_momentum60,ic_weighted_ensemble,regime_ic_weighted_ensemble"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Score causal mean-model candidates by daily cross-sectional IC.")
    parser.add_argument("--forecast-start-date", required=True)
    parser.add_argument("--forecast-end-date", required=True)
    parser.add_argument("--initial-annualized-csv", default=None)
    parser.add_argument("--history-start-date", default=None)
    parser.add_argument("--history-end-date", default=None)
    parser.add_argument("--cluster-mapping", default=builder.DEFAULT_CLUSTER_MAPPING)
    parser.add_argument("--provider-uri", default=builder.DEFAULT_PROVIDER_URI)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--candidates", default=DEFAULT_CANDIDATES)
    parser.add_argument("--window", type=int, default=252)
    parser.add_argument("--min-periods", type=int, default=20)
    parser.add_argument("--asof-lag", type=int, default=1)
    parser.add_argument("--multi-windows", default="20,60,120,252")
    parser.add_argument("--ensemble-ewma-spans", default="20,60,120,252")
    parser.add_argument("--ensemble-momentum-windows", default="20,60,120")
    parser.add_argument("--ensemble-vol-adjusted-windows", default="60,120")
    parser.add_argument("--ic-lookback", type=int, default=60)
    parser.add_argument("--ic-min-periods", type=int, default=20)
    parser.add_argument("--shrink-target", default="none", choices=builder.SHRINK_TARGET_CHOICES)
    parser.add_argument("--shrink-alpha", type=float, default=1.0)
    parser.add_argument("--winsor-quantile", type=float, default=None)
    parser.add_argument("--regime-benchmark", default="SH510300")
    parser.add_argument("--max-tickers", type=int, default=None)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def split_candidates(value: str) -> list[str]:
    return [item.strip() for item in str(value).split(",") if item.strip()]


def candidate_to_namespace(base: argparse.Namespace, candidate: str) -> argparse.Namespace:
    args = argparse.Namespace(**vars(base))
    args.mean_model = candidate
    if candidate.startswith("ewma") and candidate != "ewma":
        args.mean_model = "ewma"
        args.ewma_span = int(candidate.replace("ewma", ""))
    elif candidate.startswith("momentum") and candidate != "momentum":
        args.mean_model = "momentum"
        args.momentum_window = int(candidate.replace("momentum", ""))
    elif candidate.startswith("vol_adjusted_momentum") and candidate != "vol_adjusted_momentum":
        args.mean_model = "vol_adjusted_momentum"
        args.momentum_window = int(candidate.replace("vol_adjusted_momentum", ""))
    elif candidate in builder.MEAN_MODEL_CHOICES:
        args.mean_model = candidate
    else:
        raise ValueError(f"Unsupported candidate spec: {candidate}")
    args.ewma_span = getattr(args, "ewma_span", 60)
    args.momentum_window = getattr(args, "momentum_window", 60)
    args.vol_window = getattr(args, "vol_window", 60)
    args.multi_window_weights = ""
    args.mu_scale = 1.0
    args.no_initial_fallback = True
    args.regime_fast_ma = 20
    args.regime_slow_ma = 60
    args.regime_vol_window = 20
    args.regime_vol_lookback = 120
    return args


def pearson_ic(signal: pd.Series, forward_return: pd.Series) -> float:
    work = pd.DataFrame({"signal": signal, "forward_return": forward_return}).dropna()
    if len(work) < 3 or work["signal"].nunique() < 2 or work["forward_return"].nunique() < 2:
        return math.nan
    value = work["signal"].corr(work["forward_return"], method="pearson")
    return float(value) if pd.notna(value) else math.nan


def spearman_ic(signal: pd.Series, forward_return: pd.Series) -> float:
    work = pd.DataFrame({"signal": signal, "forward_return": forward_return}).dropna()
    if len(work) < 3 or work["signal"].nunique() < 2 or work["forward_return"].nunique() < 2:
        return math.nan
    value = work["signal"].corr(work["forward_return"], method="spearman")
    return float(value) if pd.notna(value) else math.nan


def daily_scores(candidate: str, signal: pd.DataFrame, forward_returns: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for date_value in signal.index.intersection(forward_returns.index):
        signal_row = pd.to_numeric(signal.loc[date_value], errors="coerce")
        forward_row = pd.to_numeric(forward_returns.loc[date_value], errors="coerce")
        valid = pd.DataFrame({"signal": signal_row, "forward_return": forward_row}).dropna()
        direction_hit = np.nan
        top_decile_spread = np.nan
        if not valid.empty:
            direction_mask = valid["signal"].abs() > 1e-12
            if direction_mask.any():
                direction_hit = float((np.sign(valid.loc[direction_mask, "signal"]) == np.sign(valid.loc[direction_mask, "forward_return"])).mean())
            if len(valid) >= 10 and valid["signal"].nunique() >= 3:
                ranks = valid["signal"].rank(method="first", pct=True)
                top = valid.loc[ranks >= 0.9, "forward_return"].mean()
                bottom = valid.loc[ranks <= 0.1, "forward_return"].mean()
                top_decile_spread = float(top - bottom) if pd.notna(top) and pd.notna(bottom) else np.nan
        rows.append(
            {
                "candidate": candidate,
                "forecast_date": pd.Timestamp(date_value).strftime("%Y-%m-%d"),
                "rows": int(len(valid)),
                "coverage": float(len(valid) / max(len(signal_row), 1)),
                "spearman_ic": spearman_ic(signal_row, forward_row),
                "pearson_ic": pearson_ic(signal_row, forward_row),
                "direction_accuracy": direction_hit,
                "top_decile_forward_spread": top_decile_spread,
                "mean_abs_signal": float(valid["signal"].abs().mean()) if not valid.empty else np.nan,
            }
        )
    return pd.DataFrame(rows)


def summarize_scores(daily: pd.DataFrame) -> pd.DataFrame:
    if daily.empty:
        return pd.DataFrame()
    summary = (
        daily.groupby("candidate", dropna=False)
        .agg(
            days=("forecast_date", "nunique"),
            avg_rows=("rows", "mean"),
            avg_coverage=("coverage", "mean"),
            avg_spearman_ic=("spearman_ic", "mean"),
            median_spearman_ic=("spearman_ic", "median"),
            positive_spearman_rate=("spearman_ic", lambda values: float((pd.to_numeric(values, errors="coerce") > 0.0).mean())),
            avg_pearson_ic=("pearson_ic", "mean"),
            avg_direction_accuracy=("direction_accuracy", "mean"),
            avg_top_decile_forward_spread=("top_decile_forward_spread", "mean"),
            avg_mean_abs_signal=("mean_abs_signal", "mean"),
        )
        .reset_index()
        .sort_values(["avg_spearman_ic", "avg_top_decile_forward_spread"], ascending=[False, False])
    )
    return summary


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser().resolve()
    if output_dir.exists():
        if not args.overwrite:
            raise FileExistsError(f"output dir exists; pass --overwrite to replace: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    inferred_history_start, inferred_history_end = builder.infer_window_from_name(args.initial_annualized_csv)
    history_start_date = args.history_start_date or inferred_history_start or builder.default_history_start(args.forecast_start_date)
    tickers = builder.static_builder.read_cluster_tickers(Path(args.cluster_mapping).expanduser().resolve())
    if args.max_tickers is not None:
        tickers = tickers[: int(args.max_tickers)]
    if args.regime_benchmark and str(args.regime_benchmark).upper() not in tickers:
        tickers = tickers + [str(args.regime_benchmark).upper()]
    load_start = min(pd.Timestamp(history_start_date), pd.Timestamp(args.forecast_start_date)).strftime("%Y-%m-%d")
    close = builder.load_close_panel(
        tickers,
        provider_uri=args.provider_uri,
        start_date=load_start,
        end_date=args.forecast_end_date,
    )
    daily_returns = close.pct_change(fill_method=None)
    forward_returns = builder.forward_return_panel(close)
    forecast_mask = (close.index >= pd.Timestamp(args.forecast_start_date)) & (close.index <= pd.Timestamp(args.forecast_end_date))

    candidate_frames: list[pd.DataFrame] = []
    manifest_candidates: list[dict[str, object]] = []
    selected_tickers = builder.static_builder.read_cluster_tickers(Path(args.cluster_mapping).expanduser().resolve())
    if args.max_tickers is not None:
        selected_tickers = selected_tickers[: int(args.max_tickers)]
    for candidate in split_candidates(args.candidates):
        model_args = candidate_to_namespace(args, candidate)
        signal, _count, _source, metadata = builder.build_mean_model_panel(daily_returns, close, model_args)
        signal = signal.loc[forecast_mask, selected_tickers]
        candidate_daily = daily_scores(candidate, signal, forward_returns.loc[forecast_mask, selected_tickers])
        candidate_frames.append(candidate_daily)
        manifest_candidates.append({"candidate": candidate, "metadata": metadata})

    daily = pd.concat(candidate_frames, ignore_index=True) if candidate_frames else pd.DataFrame()
    summary = summarize_scores(daily)
    daily_path = output_dir / "causal_mean_model_daily_ic.csv"
    summary_path = output_dir / "causal_mean_model_summary.csv"
    manifest_path = output_dir / "manifest.json"
    daily.to_csv(daily_path, index=False)
    summary.to_csv(summary_path, index=False)
    manifest_path.write_text(
        json.dumps(
            {
                "mode": "causal_mean_model_ic_audit",
                "forecast_start_date": args.forecast_start_date,
                "forecast_end_date": args.forecast_end_date,
                "history_start_date": history_start_date,
                "candidates": manifest_candidates,
                "daily_path": str(daily_path),
                "summary_path": str(summary_path),
            },
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )
    print(f"Wrote candidate daily IC: {daily_path}")
    print(f"Wrote candidate summary: {summary_path}")
    if not summary.empty:
        print(summary.head(20).to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())