"""Production forecast-mu override preparation.

The default production mean source is a causal EWMA60 panel shrunk toward zero
with alpha=0.75.  The same Route-A-style override contract can also carry
trend-aware rolling mean models generated by ``build_rolling_mean_route_a_override``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

from .constants import (
    PRODUCTION_FORECAST_MU_ASOF_LAG,
    PRODUCTION_FORECAST_MU_EWMA_SPAN,
    PRODUCTION_FORECAST_MU_METHOD,
    PRODUCTION_FORECAST_MU_MIN_PERIODS,
    PRODUCTION_FORECAST_MU_MISSING_FILL,
    PRODUCTION_FORECAST_MU_SHRINK_ALPHA,
    PRODUCTION_FORECAST_MU_SHRINK_TARGET,
    REPO_ROOT,
)
from .infra import _run_command


FORECAST_MU_METHOD_CHOICES = (PRODUCTION_FORECAST_MU_METHOD, "route_a")
FORECAST_MU_MODEL_CHOICES = (
    "rolling_mean",
    "ewma",
    "multi_window_mean",
    "momentum",
    "vol_adjusted_momentum",
    "ic_weighted_ensemble",
    "regime_ic_weighted_ensemble",
    "regime_switch_ewma_multi_window",
    "regime_switch_ewma_shrink",
)


def _compact_date(value: str) -> str:
    return value.replace("-", "")


def _alpha_tag(value: float) -> str:
    return f"{value:g}".replace(".", "p")


def _model_tag(args: argparse.Namespace) -> str:
    model = str(getattr(args, "forecast_mu_model", "ewma"))
    if model == "ewma":
        span = int(getattr(args, "forecast_mu_ewma_span", PRODUCTION_FORECAST_MU_EWMA_SPAN))
        return f"ewma{span}"
    aliases = {
        "regime_switch_ewma_shrink": "rs_ewma_shrink",
        "regime_switch_ewma_multi_window": "rs_ewma_multi",
        "regime_ic_weighted_ensemble": "rs_ic_ens",
        "ic_weighted_ensemble": "ic_ens",
        "vol_adjusted_momentum": "vol_mom",
        "multi_window_mean": "multi_mean",
        "rolling_mean": "roll_mean",
    }
    if model in aliases:
        return aliases[model]
    return model


def _default_output_dir(args: argparse.Namespace, start_date: str, end_date: str) -> Path:
    temp_dir = Path(args.temp_dir).expanduser().resolve()
    alpha = _alpha_tag(float(getattr(args, "forecast_mu_shrink_alpha", PRODUCTION_FORECAST_MU_SHRINK_ALPHA)))
    return temp_dir / (
        f"fmu_{_model_tag(args)}_"
        f"s{alpha}_{_compact_date(start_date)}_{_compact_date(end_date)}"
    )


def normalize_forecast_mu_args(args: argparse.Namespace) -> None:
    """Normalize production forecast-mu args before path resolution."""
    if getattr(args, "mean_override_csv", None):
        return
    if getattr(args, "forecast_mu_method", "route_a") == "route_a":
        return
    if args.forecast_mu_method != PRODUCTION_FORECAST_MU_METHOD:
        raise ValueError(
            f"Unsupported forecast_mu_method={args.forecast_mu_method!r}; "
            f"production is locked to {PRODUCTION_FORECAST_MU_METHOD!r}."
        )

    forecast_start = args.forecast_mu_start_date or args.route_a_start_date or args.start_date
    output_dir = (
        Path(args.forecast_mu_output_dir).expanduser().resolve()
        if args.forecast_mu_output_dir
        else Path(args.route_a_output_dir).expanduser().resolve()
        if args.route_a_output_dir
        else _default_output_dir(args, forecast_start, args.end_date)
    )

    args.forecast_mu_start_date = forecast_start
    args.forecast_mu_output_dir = str(output_dir)
    args.route_a_start_date = forecast_start
    args.route_a_output_dir = str(output_dir)
    if args.mode != "reuse-route-a":
        print(
            f"[INFO] forecast_mu_method={args.forecast_mu_method} supplied; "
            f"switching --mode {args.mode} -> reuse-route-a so the bridge consumes "
            "the generated production forecast-mu files."
        )
        args.mode = "reuse-route-a"


def _validate_status(status: pd.DataFrame, *, allow_incomplete: bool) -> None:
    if "status" not in status.columns:
        raise ValueError("forecast-mu status file is missing the status column")
    bad = status.loc[status["status"].astype(str) != "ok"].copy()
    if bad.empty:
        return
    if allow_incomplete:
        print(f"[WARN] Production forecast-mu has {len(bad)} incomplete instruments; continuing by request.")
        return
    preview = bad[["instrument", "status", "message"]].head(20).to_string(index=False)
    raise ValueError(
        "Production forecast-mu coverage is incomplete. Pass --forecast-mu-allow-incomplete "
        f"to continue anyway. First bad rows:\n{preview}"
    )


def _read_cluster_mapping_instruments(path: Path) -> list[str]:
    instruments: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        instruments.append(line.split()[0].upper())
    return instruments


def _instrument_universe_sha1(instruments: list[str]) -> str:
    payload = "\n".join(sorted(set(instruments))).encode("utf-8")
    return hashlib.sha1(payload).hexdigest()


def _validate_status_universe(
    status: pd.DataFrame,
    *,
    cluster_mapping_path: Path,
    output_dir: Path,
) -> list[str]:
    if "instrument" not in status.columns:
        raise ValueError(f"forecast-mu status file is missing the instrument column: {output_dir}")
    requested = set(_read_cluster_mapping_instruments(cluster_mapping_path))
    existing = set(status["instrument"].astype(str).str.upper())
    missing = sorted(requested - existing)
    extra = sorted(existing - requested)
    if missing or extra:
        missing_preview = ", ".join(missing[:20]) + (" ..." if len(missing) > 20 else "")
        extra_preview = ", ".join(extra[:20]) + (" ..." if len(extra) > 20 else "")
        raise ValueError(
            "Production forecast-mu directory was built for a different instrument universe. "
            f"output_dir={output_dir}; cluster_mapping={cluster_mapping_path}; "
            f"missing_current={len(missing)} [{missing_preview}]; "
            f"extra_existing={len(extra)} [{extra_preview}]. "
            "Use a fresh --forecast-mu-output-dir or pass --forecast-mu-overwrite after changing the pool."
        )
    return sorted(requested)


def _expected_forecast_mu_config(args: argparse.Namespace) -> dict[str, object]:
    return {
        "mean_model": str(getattr(args, "forecast_mu_model", "ewma")),
        "window": int(getattr(args, "forecast_mu_window", 252)),
        "ewma_span": int(getattr(args, "forecast_mu_ewma_span", PRODUCTION_FORECAST_MU_EWMA_SPAN)),
        "multi_windows": getattr(args, "forecast_mu_multi_windows", "20,60,120,252"),
        "multi_window_weights": getattr(args, "forecast_mu_multi_window_weights", ""),
        "momentum_window": int(getattr(args, "forecast_mu_momentum_window", 60)),
        "vol_window": int(getattr(args, "forecast_mu_vol_window", 60)),
        "ensemble_ewma_spans": getattr(args, "forecast_mu_ensemble_ewma_spans", "20,60,120,252"),
        "ensemble_momentum_windows": getattr(args, "forecast_mu_ensemble_momentum_windows", "20,60,120"),
        "ensemble_vol_adjusted_windows": getattr(args, "forecast_mu_ensemble_vol_adjusted_windows", "60,120"),
        "ic_lookback": int(getattr(args, "forecast_mu_ic_lookback", 60)),
        "ic_min_periods": int(getattr(args, "forecast_mu_ic_min_periods", 20)),
        "regime_benchmark": getattr(args, "forecast_mu_regime_benchmark", "SH510300"),
        "regime_fast_ma": int(getattr(args, "forecast_mu_regime_fast_ma", 20)),
        "regime_slow_ma": int(getattr(args, "forecast_mu_regime_slow_ma", 60)),
        "regime_vol_window": int(getattr(args, "forecast_mu_regime_vol_window", 20)),
        "regime_vol_lookback": int(getattr(args, "forecast_mu_regime_vol_lookback", 120)),
        "regime_risk_off_shrink_alpha": float(getattr(args, "forecast_mu_regime_risk_off_shrink_alpha", 0.50)),
        "mu_scale": float(getattr(args, "forecast_mu_scale", 1.0)),
        "shrink_target": getattr(args, "forecast_mu_shrink_target", PRODUCTION_FORECAST_MU_SHRINK_TARGET),
        "shrink_alpha": float(getattr(args, "forecast_mu_shrink_alpha", PRODUCTION_FORECAST_MU_SHRINK_ALPHA)),
        "winsor_quantile": getattr(args, "forecast_mu_winsor_quantile", None),
        "min_periods": int(getattr(args, "forecast_mu_min_periods", PRODUCTION_FORECAST_MU_MIN_PERIODS)),
        "asof_lag": int(getattr(args, "forecast_mu_asof_lag", PRODUCTION_FORECAST_MU_ASOF_LAG)),
        "missing_mu_fill": getattr(args, "forecast_mu_missing_fill", PRODUCTION_FORECAST_MU_MISSING_FILL),
    }


def _same_config_value(left: object, right: object) -> bool:
    if left is None or right is None:
        return left is right
    if isinstance(left, float) or isinstance(right, float):
        try:
            return abs(float(left) - float(right)) <= 1e-12
        except (TypeError, ValueError):
            return False
    return left == right


def _validate_reuse_config(args: argparse.Namespace, output_dir: Path) -> None:
    manifest_path = output_dir / "production_forecast_mu_manifest.json"
    if not manifest_path.exists():
        print(
            f"[WARN] Reusing forecast-mu dir without production manifest; "
            f"cannot verify model config: {output_dir}"
        )
        return
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected = _expected_forecast_mu_config(args)
    mismatches: list[str] = []
    for key, expected_value in expected.items():
        actual_value = manifest.get(key)
        if not _same_config_value(actual_value, expected_value):
            mismatches.append(f"{key}: existing={actual_value!r}, requested={expected_value!r}")
    if mismatches:
        preview = "; ".join(mismatches[:12])
        raise ValueError(
            "Production forecast-mu directory was built with a different model config. "
            f"output_dir={output_dir}; {preview}. "
            "Use a fresh --forecast-mu-output-dir or pass --forecast-mu-overwrite."
        )


def _write_production_manifest(args: argparse.Namespace, output_dir: Path, status: pd.DataFrame) -> None:
    cluster_mapping_path = Path(args.cluster_mapping_path).expanduser().resolve()
    instruments = _read_cluster_mapping_instruments(cluster_mapping_path)
    manifest = {
        "mode": "production_forecast_mu_override",
        "forecast_mu_method": PRODUCTION_FORECAST_MU_METHOD,
        **_expected_forecast_mu_config(args),
        "forecast_start_date": args.forecast_mu_start_date,
        "forecast_end_date": args.end_date,
        "history_start_date": args.forecast_mu_history_start_date,
        "initial_annualized_csv": args.forecast_mu_initial_annualized_csv,
        "output_dir": str(output_dir),
        "cluster_mapping_path": str(cluster_mapping_path),
        "instrument_universe_sha1": _instrument_universe_sha1(instruments),
        "tickers_requested": int(len(status)),
        "tickers_ok": int((status["status"].astype(str) == "ok").sum()),
        "mu_preset": args.mu_preset,
        "mean_overlay_mode": args.mean_overlay_mode,
    }
    (output_dir / "production_forecast_mu_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True),
        encoding="utf-8",
    )


def prepare_forecast_mu_route_a(args: argparse.Namespace, paths: dict[str, Path]) -> None:
    """Create or validate the production forecast-mu Route-A override directory."""
    if getattr(args, "mean_override_csv", None):
        return
    if getattr(args, "forecast_mu_method", "route_a") == "route_a":
        return

    output_dir = paths["route_a_output_dir"]
    status_path = output_dir / "rolling_mean_override_status.csv"
    if output_dir.exists() and not args.forecast_mu_overwrite:
        if not status_path.exists():
            raise FileExistsError(
                f"forecast-mu output dir exists without status CSV: {output_dir}. "
                "Pass --forecast-mu-overwrite to rebuild it, or use --forecast-mu-method route_a."
            )
        status = pd.read_csv(status_path)
        cluster_mapping_path = Path(args.cluster_mapping_path).expanduser().resolve()
        requested_instruments = _validate_status_universe(
            status,
            cluster_mapping_path=cluster_mapping_path,
            output_dir=output_dir,
        )
        _validate_reuse_config(args, output_dir)
        _validate_status(status, allow_incomplete=args.forecast_mu_allow_incomplete)
        _write_production_manifest(args, output_dir, status)
        print(
            f"[INFO] Reusing production forecast-mu dir: {output_dir} "
            f"method={PRODUCTION_FORECAST_MU_METHOD} model={getattr(args, 'forecast_mu_model', 'ewma')} "
            f"shrink_alpha={float(getattr(args, 'forecast_mu_shrink_alpha', PRODUCTION_FORECAST_MU_SHRINK_ALPHA)):g} "
            f"ok={(status['status'].astype(str) == 'ok').sum()}/{len(status)} "
            f"universe_sha1={_instrument_universe_sha1(requested_instruments)[:12]}"
        )
        return

    command = [
        sys.executable,
        str(REPO_ROOT / "fund_pool_builder" / "build_rolling_mean_route_a_override.py"),
        "--forecast-start-date",
        args.forecast_mu_start_date,
        "--forecast-end-date",
        args.end_date,
        "--cluster-mapping",
        str(Path(args.cluster_mapping_path).expanduser().resolve()),
        "--provider-uri",
        str(args.provider_uri),
        "--output-dir",
        str(output_dir),
        "--mean-model",
        str(getattr(args, "forecast_mu_model", "ewma")),
        "--window",
        str(int(getattr(args, "forecast_mu_window", 252))),
        "--ewma-span",
        str(int(getattr(args, "forecast_mu_ewma_span", PRODUCTION_FORECAST_MU_EWMA_SPAN))),
        "--multi-windows",
        str(getattr(args, "forecast_mu_multi_windows", "20,60,120,252")),
        "--momentum-window",
        str(int(getattr(args, "forecast_mu_momentum_window", 60))),
        "--vol-window",
        str(int(getattr(args, "forecast_mu_vol_window", 60))),
        "--ensemble-ewma-spans",
        str(getattr(args, "forecast_mu_ensemble_ewma_spans", "20,60,120,252")),
        "--ensemble-momentum-windows",
        str(getattr(args, "forecast_mu_ensemble_momentum_windows", "20,60,120")),
        "--ensemble-vol-adjusted-windows",
        str(getattr(args, "forecast_mu_ensemble_vol_adjusted_windows", "60,120")),
        "--ic-lookback",
        str(int(getattr(args, "forecast_mu_ic_lookback", 60))),
        "--ic-min-periods",
        str(int(getattr(args, "forecast_mu_ic_min_periods", 20))),
        "--regime-benchmark",
        str(getattr(args, "forecast_mu_regime_benchmark", "SH510300")),
        "--regime-fast-ma",
        str(int(getattr(args, "forecast_mu_regime_fast_ma", 20))),
        "--regime-slow-ma",
        str(int(getattr(args, "forecast_mu_regime_slow_ma", 60))),
        "--regime-vol-window",
        str(int(getattr(args, "forecast_mu_regime_vol_window", 20))),
        "--regime-vol-lookback",
        str(int(getattr(args, "forecast_mu_regime_vol_lookback", 120))),
        "--regime-risk-off-shrink-alpha",
        str(float(getattr(args, "forecast_mu_regime_risk_off_shrink_alpha", 0.50))),
        "--mu-scale",
        str(float(getattr(args, "forecast_mu_scale", 1.0))),
        "--shrink-target",
        str(getattr(args, "forecast_mu_shrink_target", PRODUCTION_FORECAST_MU_SHRINK_TARGET)),
        "--shrink-alpha",
        str(float(getattr(args, "forecast_mu_shrink_alpha", PRODUCTION_FORECAST_MU_SHRINK_ALPHA))),
        "--min-periods",
        str(int(getattr(args, "forecast_mu_min_periods", PRODUCTION_FORECAST_MU_MIN_PERIODS))),
        "--asof-lag",
        str(int(getattr(args, "forecast_mu_asof_lag", PRODUCTION_FORECAST_MU_ASOF_LAG))),
        "--missing-mu-fill",
        str(getattr(args, "forecast_mu_missing_fill", PRODUCTION_FORECAST_MU_MISSING_FILL)),
        "--overwrite",
    ]
    if str(getattr(args, "forecast_mu_multi_window_weights", "")).strip():
        command.extend(["--multi-window-weights", str(args.forecast_mu_multi_window_weights)])
    if getattr(args, "forecast_mu_winsor_quantile", None) is not None:
        command.extend(["--winsor-quantile", str(args.forecast_mu_winsor_quantile)])
    if args.forecast_mu_history_start_date:
        command.extend(["--history-start-date", str(args.forecast_mu_history_start_date)])
    if args.forecast_mu_initial_annualized_csv:
        command.extend(["--initial-annualized-csv", str(args.forecast_mu_initial_annualized_csv)])
    if args.forecast_mu_no_initial_fallback:
        command.append("--no-initial-fallback")
    raw_panel_path = paths.get("raw_panel_out")
    if raw_panel_path is not None and Path(raw_panel_path).exists():
        command.extend(["--raw-panel-path", str(Path(raw_panel_path).expanduser().resolve())])

    _run_command(command, REPO_ROOT, "production forecast-mu override")
    if not status_path.exists():
        if getattr(args, "dry_run", False):
            return
        raise FileNotFoundError(f"forecast-mu builder did not write status CSV: {status_path}")
    status = pd.read_csv(status_path)
    _validate_status(status, allow_incomplete=args.forecast_mu_allow_incomplete)
    _write_production_manifest(args, output_dir, status)
